name: cv_datagen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  # - scikit-learn
  - xgboost
  - shap
  - matplotlib
  - pyvista
  - ocp
  - pyside6
  - pyyaml
